services:
  - type: static_site
    name: anufa-ecommerce
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://anufa-backend.onrender.com
      - key: VITE_AI_API_BASE_URL
        value: https://anufa-ai-service.onrender.com
