services:
  - type: web
    name: ai-ecommerce-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: anufa-secret-key-2024-production
    healthCheckPath: /actuator/health
